const users=[
  {
    "id": 101,
    "name": "Aisha Patel",
    "username": "aisha.p",
    "email": "aisha.patel@example.com",
    "age": 29,
    "gender": "Female",
    "isActive": true,
    "roles": ["user", "editor"],
    "profile": {"bio": "Frontend developer and coffee enthusiast.", "avatarUrl": "https://example.com/avatars/101.png"},
    "contact": {"phone": "+1-415-555-0123", "address": {"street": "12 Market St", "city": "San Francisco", "state": "CA", "zip": "94103", "country": "USA"}},
    "preferences": {"newsletter": true, "notifications": {"email": true, "sms": false}, "theme": "dark"},
    "settings": {"language": "en-US", "timezone": "America/Los_Angeles"},
    "stats": {"posts": 24, "followers": 430, "following": 180, "lastLogin": "2026-04-25T09:12:00Z"},
    "posts": [
      {"postId": 9001, "title": "State management patterns", "created_at": "2026-03-10T14:22:00Z", "snippet": "Comparing Redux, MobX and hooks...", "tags": ["react","frontend"]}
    ],
    "friends": [102, 104],
    "created_at": "2023-08-01T10:00:00Z",
    "updated_at": "2026-04-20T08:00:00Z"
  },
  {
    "id": 102,
    "name": "Carlos Mendez",
    "username": "carlosm",
    "email": "carlos.mendez@example.com",
    "age": 34,
    "gender": "Male",
    "isActive": false,
    "roles": ["user"],
    "profile": {"bio": "Back-end engineer, marathoner.", "avatarUrl": "https://example.com/avatars/102.png"},
    "contact": {"phone": "+52-55-1234-5678", "address": {"street": "Calle 45 #120", "city": "Mexico City", "state": "CDMX", "zip": "06700", "country": "Mexico"}},
    "preferences": {"newsletter": false, "notifications": {"email": true, "sms": true}, "theme": "light"},
    "settings": {"language": "es-MX", "timezone": "America/Mexico_City"},
    "stats": {"posts": 8, "followers": 120, "following": 60, "lastLogin": "2025-12-10T18:00:00Z"},
    "posts": [],
    "friends": [101],
    "created_at": "2022-11-11T12:30:00Z",
    "updated_at": "2025-12-11T07:05:00Z"
  },
  {
    "id": 103,
    "name": "Rina Kaur",
    "username": "rinak",
    "email": "rina.kaur@example.co.uk",
    "age": 45,
    "gender": "Female",
    "isActive": true,
    "roles": ["user", "admin"],
    "profile": {"bio": "Product manager; loves user research.", "avatarUrl": "https://example.com/avatars/103.png"},
    "contact": {"phone": "+44-20-7946-0958", "address": {"street": "Flat 4, 21 High St", "city": "London", "state": "", "zip": "SW1A 1AA", "country": "UK"}},
    "preferences": {"newsletter": true, "notifications": {"email": true, "sms": false}, "theme": "system"},
    "settings": {"language": "en-GB", "timezone": "Europe/London"},
    "stats": {"posts": 102, "followers": 2040, "following": 410, "lastLogin": "2026-04-26T20:05:00Z"},
    "posts": [
      {"postId": 9002, "title": "Roadmapping tips", "created_at": "2025-06-01T09:00:00Z", "snippet": "Prioritizing outcomes over outputs...", "tags": ["product","strategy"]}
    ],
    "friends": [101, 105, 106],
    "created_at": "2020-02-14T07:00:00Z",
    "updated_at": "2026-04-26T20:10:00Z"
  },
  {
    "id": 104,
    "name": "Liam O'Connell",
    "username": "liamoc",
    "email": "liam.oconnell@example.ie",
    "age": 52,
    "gender": "Male",
    "isActive": true,
    "roles": ["user"],
    "profile": {"bio": "DevOps engineer; tinkers with ham radios.", "avatarUrl": "https://example.com/avatars/104.png"},
    "contact": {"phone": "+353-1-555-0199", "address": {"street": "3 St. Kevin's Lane", "city": "Dublin", "state": "", "zip": "D02", "country": "Ireland"}},
    "preferences": {"newsletter": false, "notifications": {"email": false, "sms": false}, "theme": "dark"},
    "settings": {"language": "en-IE", "timezone": "Europe/Dublin"},
    "stats": {"posts": 12, "followers": 600, "following": 80, "lastLogin": "2026-04-24T06:40:00Z"},
    "posts": [],
    "friends": [101],
    "created_at": "2019-07-19T15:20:00Z",
    "updated_at": "2026-04-24T06:40:00Z"
  },
  {
    "id": 105,
    "name": "Zoe Nakamura",
    "username": "zoe_n",
    "email": "zoe.nakamura@example.jp",
    "age": 31,
    "gender": "Non-binary",
    "isActive": true,
    "roles": ["user", "moderator"],
    "profile": {"bio": "UX researcher and ceramic artist.", "avatarUrl": "https://example.com/avatars/105.png"},
    "contact": {"phone": "+81-3-1234-5678", "address": {"street": "1-2-3 Shibuya", "city": "Tokyo", "state": "Tokyo", "zip": "150-0002", "country": "Japan"}},
    "preferences": {"newsletter": true, "notifications": {"email": true, "sms": false}, "theme": "light"},
    "settings": {"language": "ja-JP", "timezone": "Asia/Tokyo"},
    "stats": {"posts": 46, "followers": 980, "following": 300, "lastLogin": "2026-04-27T01:55:00Z"},
    "posts": [
      {"postId": 9003, "title": "User interview tips", "created_at": "2026-01-15T11:00:00Z", "snippet": "How to ask non-leading questions...", "tags": ["ux","research"]}
    ],
    "friends": [103],
    "created_at": "2021-04-05T09:15:00Z",
    "updated_at": "2026-04-27T02:00:00Z"
  },
  {
    "id": 106,
    "name": "Noah Singh",
    "username": "noah.s",
    "email": "noah.singh@example.ca",
    "age": 22,
    "gender": "Male",
    "isActive": true,
    "roles": ["user"],
    "profile": {"bio": "Computer science student and open-source contributor.", "avatarUrl": "https://example.com/avatars/106.png"},
    "contact": {"phone": "+1-647-555-0102", "address": {"street": "88 College St", "city": "Toronto", "state": "ON", "zip": "M5G 1K7", "country": "Canada"}},
    "preferences": {"newsletter": true, "notifications": {"email": true, "sms": true}, "theme": "system"},
    "settings": {"language": "en-CA", "timezone": "America/Toronto"},
    "stats": {"posts": 3, "followers": 45, "following": 70, "lastLogin": "2026-04-20T13:20:00Z"},
    "posts": [],
    "friends": [103],
    "created_at": "2024-09-10T16:45:00Z",
    "updated_at": "2026-04-20T13:20:00Z"
  }
]

module.exports= users;